### PR TITLE
[Major] Zeta version

### PR DESCRIPTION
**Pull request by aryamanarora**
Mega-update. See below.

### CODE REVIEW

**Comment by aryamanarora** [comment]
Okay so this will just be our mega-update lol:

- [ ] Improve user experience by abstracting away all the complicated stuff when loading a dataset for ReFT training.
- [ ] Ablation studies on LoReFT.
- [ ] Reward modelling and paired-preference learning.
- [ ] DoRA hparam replications.
- [ ] Maybe also QLoReFT (quantised model + full-precision ReFT).

**Comment by frankaging** [comment]
@PinetreePantry Hey Peter, do you want to look into the gradio demo? just do our chat-model thing in our README first? thanks!

**Comment by aryamanarora** [comment]
Ok this is done!
- #43 

Will write up docs to explain how to use `ReftDataset`.

**Comment by frankaging** [comment]
Removing GLUE without head-tuning as the goal. Tried offline with the current hyperparameters, it does not work well.

**Pull request merged**
